import os
import json
import time
from playwright.sync_api import sync_playwright

def run_scraper():
    with sync_playwright() as p:
        # Launch a professional desktop-grade browser
        browser = p.chromium.launch(headless=True)
        # Set a standard desktop screen size
        context = browser.new_context(viewport={'width': 1280, 'height': 800})
        page = context.new_page()

        try:
            print("Master Strategy: Let Tradetron guide us.")
            # 1. We go to the Deployed page directly. Tradetron will auto-redirect us to login.
            page.goto("https://tradetron.tech/deployed-strategies", wait_until="domcontentloaded")
            
            # 2. Use Playwright's 'Master' selectors to fill credentials
            print("Step: Filling Credentials...")
            page.get_by_placeholder("Email").fill(os.environ.get("TT_EMAIL").strip())
            page.get_by_placeholder("Password").fill(os.environ.get("TT_PASSWORD").strip())
            
            # 3. Handle Altcha with Playwright's 'wait_for_function' (The Pro way)
            print("Step: Waiting for Altcha verification...")
            # We click the widget
            page.locator("altcha-widget").click(position={"x": 10, "y": 10})
            # MASTER LOGIC: Wait until the hidden solution is generated by the server
            page.wait_for_function(
                "() => { const el = document.querySelector('input[name=\"altcha\"]'); return el && el.value.length > 20; }",
                timeout=30000
            )
            print("Altcha Verified!")

            # 4. Master Click: Perform login
            # We wait for the 'networkidle' to ensure no security scripts are still running
            page.get_by_role("button", name="Sign In").click()
            
            # 5. Master Wait: Instead of waiting for a URL, wait for a 'Success' element
            print("Step: Entering Account...")
            page.wait_for_selector("text='Logout', text='Deployed'", timeout=60000)
            print("LOGIN SUCCESSFUL!")

            # 6. Ensure we are on the Data Page
            if "/deployed-strategies" not in page.url:
                page.goto("https://tradetron.tech/deployed-strategies", wait_until="networkidle")
            
            # 7. Master Scrape: Extract clean JSON
            print("Step: Extracting P&L...")
            strategies = page.evaluate("""() => {
                let items = [];
                // This selector targets both 'Pro' rows and 'Lite' cards
                const blocks = document.querySelectorAll('tr, .strategy-card, .deployment-card, .deployed-strategy-block');
                blocks.forEach(b => {
                    let txt = b.innerText;
                    if (txt.includes('by ') && (txt.includes('₹') || txt.includes('Rs.'))) {
                        let lines = txt.split('\\n').map(l => l.trim()).filter(l => l.length > 0);
                        let name = lines[0].replace(/^\\d+\\.\\s*/, '').split(' by ')[0].trim();
                        let pnlMatches = txt.match(/[₹Rs\\.]\\s?([+-]?[\\d,]+\\.?\\d*)/gi);
                        if (pnlMatches) {
                            let lastMatch = pnlMatches[pnlMatches.length - 1];
                            let val = lastMatch.replace(/[₹Rs\\.\\s,]/gi, '');
                            let pnl = parseFloat(val) || 0.0;
                            if (lastMatch.toUpperCase().includes('K')) pnl *= 1000;
                            if (lastMatch.toUpperCase().includes('L')) pnl *= 100000;
                            if (lastMatch.includes('-')) pnl *= -1;
                            items.push({ name, pnl });
                        }
                    }
                });
                return [...new Map(items.map(i => [i.name, i])).values()];
            }""")

            print(f"COMPLETE: Found {len(strategies)} strategies.")
            with open("data.json", "w") as f:
                json.dump({"last_updated": time.strftime("%H:%M:%S"), "strategies": strategies}, f, indent=4)

        except Exception as e:
            print(f"MASTER ERROR: {str(e)}")
            with open("data.json", "w") as f:
                json.dump({"error": str(e), "url": page.url}, f)
        
        browser.close()

if __name__ == "__main__":
    run_scraper()
